/* blueprint-lines.js — second pass: gate-specific nuance for each of the 6 lines.

   ORIGINAL CONTENT, compositional by construction: each entry expresses a gate's
   theme (from blueprint-codes.js) through one line's mode — Line 1 foundation,
   2 natural, 3 experimenter, 4 networker, 5 deliverer, 6 exemplar. Grounded in
   the public-domain I Ching line positions; NOT the Gene Keys' copyrighted
   per-line text. A first pass to be deepened. Merged into window.VersorCodes
   (loads after blueprint-codes.js).

   GATE_LINES[gate] = [line1, line2, line3, line4, line5, line6]. */
(function (g) {
  'use strict';
  const GATE_LINES = {
    1:  ['Roots its originality in solid craft — masters the fundamentals before the new can flow.', 'Creates effortlessly when left alone; the spark is drawn out by the right call, never forced.', 'Finds an original voice through failed drafts — creativity earned by making a mess.', 'The new is born among trusted collaborators; creative fire moves through the right circle.', 'Others look to it as the creative one and expect it to deliver vision on demand.', 'Matures into a creative exemplar — eventually models how to bring beauty into being.'],
    2:  ['Finds direction by grounding deeply in itself before letting life point the way.', 'Naturally knows which way to face; the sense of direction surfaces when it stops steering.', 'Learns its true heading by wandering, getting lost, and course-correcting through experience.', 'The right people reveal the way; direction comes through relationships and belonging.', 'Others look to it for direction and call on it to lead the way forward.', 'Becomes a trusted compass for others, modeling how to follow life’s deeper current.'],
    3:  ['Steadies the early chaos by anchoring in first principles before building anything.', 'A natural ordererer of confusion — does best when not pressured to produce on cue.', 'Turns mess into form by trial and error; learns what works by living the disorder.', 'Orders the new through allies; the right partnerships turn chaos into structure.', 'Looked to for getting things off the ground; pressured to make order out of the muddle.', 'Eventually an exemplar of starting well — shows others how beginnings find their footing.'],
    4:  ['Grounds its answers in study; needs the underlying logic before it will commit to a view.', 'Understanding comes naturally and at ease; pushed for answers, it freezes.', 'Earns real understanding by testing wrong answers until the right one holds.', 'Thinks things through with trusted others; insight arrives in conversation.', 'Others bring it their questions, expecting solutions it’s called to provide.', 'Matures into a patient teacher — models holding the question until truth ripens.'],
    5:  ['Builds its sense of timing on solid routine — patience rooted in a dependable base.', 'Naturally unhurried; its right rhythm shows when it isn’t rushed to act.', 'Learns patience the hard way, through mistimed moves and the cost of forcing.', 'Times things through the group; the network signals when the moment is ripe.', 'Others wait on its timing and lean on it to know when to move.', 'Becomes an exemplar of right timing — trusted to wait well and act at the hour.'],
    6:  ['Defends its boundaries from a settled inner base — knows its limits before it engages.', 'A naturally clear edge; intimacy and distance find their own healthy balance when unforced.', 'Learns where the boundary belongs through friction, clashes, and reconciliations.', 'Negotiates closeness through relationship; the boundary is set with specific people.', 'Others look to it to broker peace; called to hold the line and make the truce.', 'Matures into an exemplar of intimacy — models conflict met without losing the self.'],
    7:  ['Leads from a foundation of preparation; earns the role by knowing the ground first.', 'A natural authority others simply follow; works best when not jockeying for the lead.', 'Learns to lead through trial — wrong calls and hard-won course-corrections.', 'Leads through alliances and friendships; guides by who it knows and trusts.', 'The one called to steer the group; others project the leader’s mantle onto it.', 'Becomes the elder statesperson — an objective, trusted model of service-led leadership.'],
    8:  ['Builds its contribution on a studied foundation before offering its style.', 'Its authentic note shines naturally; forcing it to perform flattens it.', 'Finds its real voice by trying on styles that don’t fit until the true one does.', 'Contributes through collaboration; its individuality lands best within the right group.', 'Looked to for the original touch; expected to supply the distinctive contribution.', 'Models authentic self-offering — shows others how to give their true difference.'],
    9:  ['Grounds its focus in fundamentals; concentrates best from a secure, prepared base.', 'Naturally absorbed in the detail; pushed to focus on demand, it scatters.', 'Learns what deserves attention by chasing the wrong details first.', 'Focuses through the group; the right people sharpen what it concentrates on.', 'Others rely on its focus to finish things; called to bring the detail home.', 'Becomes an exemplar of focused power — models attention that completes.'],
    10: ['Anchors self-conduct in deep self-study; behaves from a known inner foundation.', 'Naturally itself; most authentic when left to simply be, not pressured to perform a self.', 'Finds its true way of being through trial — self-betrayals teach self-loyalty.', 'Learns to love and behave as itself through relationships and mirroring.', 'Others look to how it carries itself; projected onto as a model of conduct.', 'Becomes a living example of self-respect — shows others how to walk their own way.'],
    11: ['Roots its ideas in study; the vision rests on a researched foundation.', 'Ideas arrive naturally and at ease; forced to produce them, the well goes quiet.', 'Sorts inspiring ideas from noise by testing many and discarding the duds.', 'Its ideas catch fire among the right people; meaning is shared into being.', 'Others come to it for ideas and expect the vision to be supplied.', 'Becomes a keeper of meaning — models holding ideas that genuinely inspire.'],
    12: ['Grounds its expression in preparation; speaks from a studied, secure base.', 'A naturally graceful voice when moved; pushed to speak on cue, it falters.', 'Learns when to speak through the awkward cost of mistimed words.', 'Expresses through relationship; its voice lands for the people it’s bonded to.', 'Others wait on its word; called to articulate what the moment needs.', 'Becomes an exemplar of ripe expression — models speaking only what is true and timely.'],
    13: ['Holds others’ stories from a grounded, discreet inner base.', 'A naturally trusted confidant; people open up without being asked.', 'Learns discretion the hard way — through leaks, gossip, and broken trust.', 'Gathers and keeps stories through its web of relationships.', 'Others bring it their secrets; called to witness and hold what’s confided.', 'Becomes the wise listener — models compassion that draws out the truth.'],
    14: ['Builds its resources on a disciplined foundation before deploying them.', 'Competence and means come naturally; forcing the effort drains it.', 'Learns to wield its resources through trial, waste, and recovery.', 'Resources flow through relationships; the right network multiplies its means.', 'Others look to it to power the direction; expected to supply the fuel.', 'Becomes a model of empowered means — shows how skill backs a purpose.'],
    15: ['Anchors its wide range in a steady inner rhythm before extending it.', 'Naturally magnetic and humane; pushed to perform warmth, it goes flat.', 'Finds the human mean by swinging through extremes until balance lands.', 'Its embrace is expressed through relationships; range shows among people.', 'Others look to it to set the human tempo; called to model the rhythm.', 'Becomes an exemplar of humanity’s range — models the full flowering of the human.'],
    16: ['Grounds enthusiasm in practice; the leap rests on rehearsed fundamentals.', 'Skill comes naturally and at ease; forced to perform, the magic stalls.', 'Refines talent through trial — many clumsy attempts before the leap lands.', 'Skill develops through the right collaborators; enthusiasm catches in company.', 'Others look to its talent and expect it to perform on cue.', 'Becomes a master exemplar — shows others how mastery can look like play.'],
    17: ['Builds its views on researched foundations before holding an opinion.', 'Sees the pattern naturally; pressured to opine on demand, it overreaches.', 'Learns far-sight by holding wrong opinions until experience corrects them.', 'Shares its views through relationship; opinions land among the right people.', 'Others seek its opinion and expect it to organize the picture for them.', 'Becomes an exemplar of clear-seeing — models a view held open, not fixed.'],
    18: ['Grounds its corrections in study; fixes from understood fundamentals.', 'A natural eye for what’s off; forced to critique, it turns harsh.', 'Learns to correct without cruelty through its own over-judgments.', 'Improves things through relationship; mends what’s broken among its people.', 'Others bring it what needs fixing; called to restore and set things right.', 'Becomes an exemplar of integrity — models correction that heals rather than condemns.'],
    19: ['Grounds its sensitivity in a secure base so need doesn’t become clinging.', 'Naturally attuned to what others need; pushed, the antenna overwhelms.', 'Learns healthy attunement through over-reaching and rejection.', 'Reaches for belonging through close bonds and the right tribe.', 'Others rely on its sensitivity; called to sense and serve what’s needed.', 'Becomes an exemplar of attunement — models giving without losing the self.'],
    20: ['Roots its presence in inner stillness before meeting the now.', 'Naturally present; forced to be “on,” the aliveness flickers out.', 'Learns to stay present by catching itself drifting, again and again.', 'Its presence comes alive with others; the now is shared, not solo.', 'Others feel met by its presence; called to be fully here for them.', 'Becomes an exemplar of presence — models awareness awake to the moment.'],
    21: ['Earns its authority on a studied foundation; controls from understanding.', 'A natural steward; pressed to dominate, the grip becomes control.', 'Learns rightful command through overreach and the cost of control.', 'Manages its domain through relationship; authority works among allies.', 'Others put it in charge; called to take command and protect what’s theirs.', 'Becomes an exemplar of right authority — models courage that serves.'],
    22: ['Opens its heart from a secure base; grace rests on inner ground.', 'Naturally gracious; pushed to charm, it shuts down or overacts.', 'Learns emotional openness through awkward closings and re-openings.', 'Its grace shows in relationship; the open heart meets specific people.', 'Others are drawn to its grace; called to bring warmth to the room.', 'Becomes an exemplar of grace — models an openness that needs no occasion.'],
    23: ['Grounds its insight in study before translating it into plain speech.', 'Simplicity comes naturally; pressured to explain on cue, it tangles.', 'Learns clear expression by saying it badly until it lands.', 'Translates for its people; insight is made plain among trusted ears.', 'Others wait for its translation; called to make the complex simple.', 'Becomes an exemplar of clarity — models the essence caught in a single stroke.'],
    24: ['Returns to its themes from a grounded base, mining roots for fresh sense.', 'Naturally re-thinks at ease; forced to resolve on cue, it loops.', 'Breaks the loop through trial — addicted returns that finally find new ground.', 'Its returns are processed with others; meaning is found in dialogue.', 'Others bring it the unresolved; called to make new sense of old ground.', 'Becomes an exemplar of renewal — models the silence beyond compulsive thought.'],
    25: ['Grounds its open heart in self-knowledge so innocence isn’t naïveté.', 'Naturally innocent and loving; pushed, the heart armors over.', 'Learns unconditional love through wounds that harden, then soften it.', 'Its love of life shows through bonds; the open heart meets real people.', 'Others feel its spirit; called to love without condition and hold the field.', 'Becomes an exemplar of the open heart — models love of life for its own sake.'],
    26: ['Grounds its influence in integrity before it amplifies or persuades.', 'Naturally persuasive; pushed to sell, it slides into embellishment.', 'Learns honest influence through the cost of overselling.', 'Transmits through relationships; its will moves people it’s bonded to.', 'Others rely on it to carry the message; called to persuade and deliver.', 'Becomes an exemplar of artful influence — impact that leaves no trace of ego.'],
    27: ['Grounds its care in a secure base so giving doesn’t deplete it.', 'Naturally nourishing; pushed to give, it tips into self-neglect or over-care.', 'Learns the balance of care through over-giving and burning out.', 'Cares through relationship; nourishment flows to its people first.', 'Others lean on its care; called to feed and protect those around it.', 'Becomes an exemplar of nourishment — models selfless care that still keeps the self whole.'],
    28: ['Grounds its risks in preparation; stakes its life on a studied footing.', 'Naturally adventurous; forced to gamble on cue, fear takes over.', 'Finds what’s worth the risk by trial — many dead ends before meaning.', 'Takes its risks alongside others; courage is steadied by the bond.', 'Others look to its daring; called to brave what they cannot.', 'Becomes an exemplar of meaningful risk — holds life and death lightly.'],
    29: ['Grounds its commitments in a base so the yes doesn’t become overwhelm.', 'Says yes naturally; pushed to commit on cue, it over-extends.', 'Learns where to commit through over-committed, exhausting trials.', 'Commits through relationship; goes all-in alongside the right people.', 'Others rely on its follow-through; called to say yes and see it through.', 'Becomes an exemplar of devotion — models commitment that carries you through.'],
    30: ['Grounds its desire in self-knowledge so longing doesn’t consume it.', 'Naturally aspiring; pushed, the fire becomes craving and mood.', 'Learns to hold desire through being burned by it, repeatedly.', 'Its longing kindles among others; feeling is fueled in company.', 'Others feel its fire; called to carry the aspiration for the group.', 'Becomes an exemplar of feeling — models desire that warms without scorching.'],
    31: ['Grounds its leadership-voice in preparation before it speaks for others.', 'A natural voice of influence; pushed to lead on cue, it rings hollow.', 'Learns true leadership through self-serving missteps that humble it.', 'Leads through relationship; its voice carries among the people it serves.', 'Others elect it to speak for them; called to give the collective its voice.', 'Becomes an exemplar of leadership — models influence emptied of ego.'],
    32: ['Grounds its instinct for endurance in a secure, studied base.', 'Naturally senses what lasts; pushed, fear of failing distorts the read.', 'Learns what endures through ventures that fail and ones that hold.', 'Preserves through relationship; reads what will last among its people.', 'Others trust its sense of the durable; called to safeguard what should endure.', 'Becomes an exemplar of endurance — models reverence for what truly lasts.'],
    33: ['Withdraws to a grounded base to digest before it recounts.', 'Naturally reflective; pushed to share too soon, the meaning is lost.', 'Learns the value of retreat by avoiding, then finally facing, the past.', 'Processes its experience with others; the story is told to trusted ears.', 'Others seek its hindsight; called to retell what its retreat revealed.', 'Becomes an exemplar of reflection — turns private experience into revelation.'],
    34: ['Grounds its power in preparation so strength isn’t spent on busyness.', 'Naturally strong; pushed to act on cue, force replaces real response.', 'Learns to channel power through misfires and wasted effort.', 'Its strength serves the group; power is best used among others.', 'Others rely on its power; called to lend strength where it’s needed.', 'Becomes an exemplar of strength — models power that waits for the right use.'],
    35: ['Grounds its hunger in a base so the appetite doesn’t become restlessness.', 'Naturally experience-rich; pushed for more on cue, satisfaction slips.', 'Learns wisdom by devouring experiences, including the bad ones.', 'Its experiences are gathered with others; progress is shared.', 'Others look to its breadth; called to lead the way through experience.', 'Becomes an exemplar of progress — models fullness with nowhere left to chase.'],
    36: ['Steadies emotional plunges from a grounded inner base.', 'Naturally meets crisis; pushed into it unready, turbulence wins.', 'Learns to navigate the depths through being thrown again and again.', 'Moves through emotional storms with others; crisis is shared, not solo.', 'Others lean on it in crisis; called to bring humanity to the dark.', 'Becomes an exemplar of depth — compassion forged in the storm.'],
    37: ['Builds its bonds on a secure base so warmth isn’t fragile dependence.', 'A naturally warm presence; pushed, attachment turns clingy.', 'Learns equal-footed friendship through bonds that break and mend.', 'Its element is relationship itself — family and friendship made.', 'Others gather around its warmth; called to hold the bonds together.', 'Becomes an exemplar of friendship — tenderness that includes everyone.'],
    38: ['Grounds its fight in conviction so struggle has a worthy cause.', 'Naturally tenacious; pushed to fight on cue, it battles for nothing.', 'Learns which fights matter by squandering some on the wrong ones.', 'Fights for its people; the stand is taken alongside allies.', 'Others rally to its stand; called to fight the fight they can’t.', 'Becomes an exemplar of conviction — stands in quiet, settled honor.'],
    39: ['Provokes from a grounded base, knowing why it stirs the pot.', 'A natural spark; pushed to provoke on cue, it just needles.', 'Learns the art of provocation through reactions that backfire.', 'Provokes within relationships; stirs feeling among the right people.', 'Others feel its prod; called to awaken spirit where it’s gone flat.', 'Becomes an exemplar of the catalyst — the jolt that frees rather than wounds.'],
    40: ['Grounds its willing work in a base so it can also truly rest.', 'Naturally delivers; pushed past its no, it runs on empty.', 'Learns its limits through burnout and the hard lesson of the no.', 'Its work serves the bond; provides for the people it belongs to.', 'Others depend on it to deliver; called to provide, then withdraw.', 'Becomes an exemplar of will — work and rest aligned with a larger aim.'],
    41: ['Grounds its new desires in a base so the spark isn’t lost to fantasy.', 'Naturally feels the first stirring; pushed, it escapes into daydream.', 'Learns to honor the spark by chasing fantasies that lead nowhere.', 'Its new feelings ignite with others; desire is kindled in company.', 'Others catch its spark; called to initiate the next cycle of feeling.', 'Becomes an exemplar of beginnings — feeling honored as it first arises.'],
    42: ['Grounds its endings in a base so it can let cycles truly close.', 'Naturally sees things through; pushed, it grasps and can’t release.', 'Learns completion through cycles it abandoned or clung to too long.', 'Closes cycles with others; endings are seen through together.', 'Others rely on it to finish; called to bring the matter to its close.', 'Becomes an exemplar of completion — each ending met as celebration.'],
    43: ['Grounds its insight in study so the breakthrough has substance.', 'Knowing arrives naturally; pushed to produce it, the channel closes.', 'Learns to trust insight through being dismissed, then vindicated.', 'Shares its breakthroughs with others; insight lands in the right ear.', 'Others await its knowing; called to voice the breakthrough for them.', 'Becomes an exemplar of insight — models the sudden, clear seeing.'],
    44: ['Reads people from a grounded base, sensing patterns before acting.', 'A natural instinct for people; pushed, the read becomes manipulation.', 'Learns whom to trust through misreads and betrayals.', 'Its gift is the alliance itself — knows exactly who to work with.', 'Others rely on its read; called to assemble the right people.', 'Becomes an exemplar of instinct — the right alliance formed effortlessly.'],
    45: ['Grounds its gathering in a secure base before it leads the group.', 'A natural gatherer; pushed to rule, it hoards instead of shares.', 'Learns to lead the tribe through power grabbed and lost.', 'Gathers through relationship; draws its people and resources together.', 'Others look to it to provide; called to gather and distribute the wealth.', 'Becomes an exemplar of the gatherer — the many made one.'],
    46: ['Grounds its embodiment in a base so effort doesn’t turn to grind.', 'Naturally at home in the body; pushed, delight hardens into duty.', 'Finds grace through trial — clumsy effort that lands as serendipity.', 'Its delight is shared; the body’s joy comes alive among others.', 'Others feel its aliveness; called to embody what they admire.', 'Becomes an exemplar of embodiment — the body as a place of grace.'],
    47: ['Sorts confusion from a grounded base before the meaning clicks.', 'Naturally makes sense of things; pushed, the fog of oppression thickens.', 'Learns realization through stretches of not-understanding that finally resolve.', 'Its sense-making is shared; meaning surfaces in dialogue.', 'Others bring it the muddle; called to make sense of it for them.', 'Becomes an exemplar of realization — confusion transfigured into meaning.'],
    48: ['Builds its depth on a studied foundation; the well is dug deep.', 'A natural depth of skill; pushed to perform it, the fear of lack rises.', 'Learns its true capacity by hitting the limits of what it knows.', 'Its depth is drawn upon by others; skill flows through relationship.', 'Others come to its well; called to provide the depth they lack.', 'Becomes an exemplar of depth — wisdom that never runs dry.'],
    49: ['Grounds its reforms in principle so change isn’t blind reaction.', 'A natural sense of when to turn; pushed, it rejects out of reflex.', 'Learns principled change through revolts that were premature.', 'Turns with its people; revolution is made among allies.', 'Others look to it to call the change; expected to lead the turn.', 'Becomes an exemplar of revolution — renewal from the inside out.'],
    50: ['Grounds its values in study before it guards the community’s code.', 'A natural keeper of values; pushed, responsibility curdles into burden.', 'Learns to hold values in balance through the weight of getting it wrong.', 'Upholds values through relationship; guards the code for its people.', 'Others trust it to keep the standard; called to safeguard the values.', 'Becomes an exemplar of guardianship — harmony upheld for all.'],
    51: ['Meets shock by returning to fundamentals — grounds before it reacts.', 'Naturally composed when jolted; pushed to perform under it, the calm cracks.', 'Learns courage through repeated jolts — rattled, recovers, grows resilient.', 'Steadies the people around it when shock strikes; calms the circle.', 'The one others look to under sudden pressure; called to go first when it counts.', 'Becomes an exemplar of nerve — an unshakeable witness who stays awake through upheaval.'],
    52: ['Roots its stillness in a secure base; stops from solid ground.', 'Naturally still; pushed to hold tension, stress builds underneath.', 'Learns to be still through restless years that finally settle.', 'Its stillness steadies others; calm is shared in the right company.', 'Others seek its calm; called to bring stillness to the situation.', 'Becomes an exemplar of stillness — models deep, motionless concentration.'],
    53: ['Grounds new beginnings in a base so the pressure to start has footing.', 'Naturally starts cycles; pushed, restlessness overruns the readiness.', 'Learns steady development through false starts and stalled beginnings.', 'Begins alongside others; new growth takes root in company.', 'Others look to it to start things; called to set development in motion.', 'Becomes an exemplar of beginnings — models the steady, endless unfolding.'],
    54: ['Grounds its ambition in a base so the climb isn’t driven by lack.', 'A natural drive to rise; pushed, ambition turns to grasping.', 'Learns clean ambition through climbs that overreached and fell.', 'Rises through relationship; the ascent is made with the right backers.', 'Others ride its drive; called to carry the group upward.', 'Becomes an exemplar of ascent — ambition that reaches into the unseen.'],
    55: ['Grounds its abundant heart in a base so mood doesn’t rule it.', 'Naturally full of spirit; pushed, feeling swings into moodiness.', 'Learns emotional freedom by riding the wave through its lows.', 'Its fullness is shared; the heart’s richness shows among others.', 'Others feel its spirit; called to hold emotional abundance for the group.', 'Becomes an exemplar of the full heart — spirit overflowing into freedom.'],
    56: ['Grounds its stories in study so the telling carries real substance.', 'A natural storyteller; pushed for stimulation, it scatters.', 'Learns to enrich through tales that fell flat before they landed.', 'Its stories enliven the group; meaning is shared around the fire.', 'Others gather for its telling; called to enrich them with the tale.', 'Becomes an exemplar of the storyteller — meaning that intoxicates.'],
    57: ['Grounds its intuition in a base so the gut isn’t drowned by unease.', 'Naturally intuitive; pushed to explain the knowing, it second-guesses.', 'Learns to trust intuition through times it ignored, then regretted it.', 'Its intuition attunes to others; clarity sharpens in relationship.', 'Others rely on its read; called to voice what the moment knows.', 'Becomes an exemplar of intuition — immediate, luminous clarity.'],
    58: ['Grounds its zest in a base so the drive to improve isn’t mere complaint.', 'Naturally joyful; pushed, joy curdles into nagging dissatisfaction.', 'Learns vital joy through dissatisfactions that pointed the way.', 'Its vitality lifts the group; the urge to improve is shared.', 'Others catch its zest; called to energize what needs improving.', 'Becomes an exemplar of joy — causeless aliveness that wants the best for life.'],
    59: ['Grounds its closeness in a base so intimacy isn’t a tactic.', 'Naturally disarming; pushed, charm becomes a way past defenses.', 'Learns true intimacy through closeness that was forced or feigned.', 'Its gift is the bond itself — barriers dissolved with the right person.', 'Others open to it; called to break the distance and connect.', 'Becomes an exemplar of intimacy — nothing hidden between you.'],
    60: ['Grounds in its limits, building secure form from what constrains it.', 'Naturally works within limits; pushed, constraint hardens into stuckness.', 'Learns to transmute limits through constraints that first defeated it.', 'Turns limits to form with others; structure is built in company.', 'Others look to it to work the constraints; called to make the new from the limit.', 'Becomes an exemplar of the fertile limit — the just order in all things.'],
    61: ['Grounds its search for truth in study so mystery doesn’t become obsession.', 'Naturally touched by the unknown; pushed, the mind spins on the unknowable.', 'Learns to bear the mystery through obsessions that finally quieted.', 'Its wonder is shared; inspiration sparks among kindred minds.', 'Others seek its insight into why; called to voice the deeper knowing.', 'Becomes an exemplar of the mystic — touches the sacred unknown.'],
    62: ['Grounds its precision in study; orders detail from a solid base.', 'Naturally exact; pushed, precision chills into cold pedantry.', 'Learns useful precision through fussing over details that didn’t matter.', 'Names things for the group; precision serves the people around it.', 'Others rely on its exactness; called to find the right word and order.', 'Becomes an exemplar of precision — the perfect word for the thing.'],
    63: ['Grounds its doubt in study so skepticism becomes rigorous inquiry.', 'Naturally questioning; pushed, doubt corrodes into anxiety.', 'Learns sound inquiry through doubts that proved both right and wrong.', 'Tests the pattern with others; doubt is resolved in dialogue.', 'Others bring it claims to check; called to verify what holds.', 'Becomes an exemplar of inquiry — doubt resolved into truth.'],
    64: ['Grounds its many possibilities in a base so confusion can resolve.', 'Naturally imaginative; pushed to resolve on cue, the fog thickens.', 'Learns to sort the maybes by chasing possibilities that led nowhere.', 'Its possibilities take shape with others; clarity comes in company.', 'Others bring it the unresolved; called to imagine the way through.', 'Becomes an exemplar of imagination — the flash that makes it clear.'],
  };

  g.VersorCodes = Object.assign(g.VersorCodes || {}, { GATE_LINES });
})(window);
